name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.40.0 #MSRV
          - stable
          - beta
          - nightly

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Cache cargo dirs
        uses: actions/cache@v2
        with:
          path:
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ matrix.version }}-x86_64-unknown-linux-gnu-cargo-trimmed-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ matrix.version }}-x86_64-unknown-linux-gnu-cargo-build-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build book and check links
        if: matrix.version == 'stable'
        run: |
          which mdbook ||cargo install mdbook --no-default-features --features output --version 0.3.7
          which mdbook-linkcheck || cargo install mdbook-linkcheck --version 0.5.0
          mdbook build ./actix/

      - name: Clear the cargo caches
        run: |
          which cargo-cache || cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
