name: Upload documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == '!hltj/actix-book-cn'

    steps:
      - uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Upload documentation
        run: |
          cargo install mdbook --no-default-features --features output --version 0.3.7
          mdbook build ./actix/ -d ../target/doc/actix
          cp -r ./target/doc/actix/html/* ./target/doc/actix/
          rm -r ./target/doc/actix/html ./target/doc/actix/linkcheck
          git clone https://github.com/davisp/ghp-import.git
          ./ghp-import/ghp_import.py -n -p -f -m "内容更新" -r https://${{ secrets.GH_TOKEN }}@github.com/book-cn/actix.git target/doc
